#!/bin/sh

SOURCEANALYZER=$HPFORTIFY_HOME/sourceanalyzer
MEMORY="-Xmx7270M -Xms400M -Xss24M "
PROJECTID="JNI_EXAMPLE_2"

$SOURCEANALYZER -b $PROJECTID $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/darwin-x86_64/bin/ar  $@